# Generated by Django 4.2.25 on 2025-10-25 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diaryapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(blank=True, max_length=100, null=True)),
                ('USERID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='diaryapp.usermodel')),
            ],
        ),
        migrations.CreateModel(
            name='complaintsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Complaint', models.TextField(blank=True, max_length=100, null=True)),
                ('Reply', models.CharField(blank=True, max_length=100, null=True)),
                ('USERID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='diaryapp.usermodel')),
            ],
        ),
    ]
