# Generated by Django 4.2.24 on 2025-10-25 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diaryapp', '0002_feedbackmodel_complaintsmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyActivities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Day', models.DateField(blank=True, null=True)),
                ('Title', models.CharField(blank=True, max_length=100, null=True)),
                ('Description', models.TextField(blank=True, null=True)),
                ('USERID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='diaryapp.usermodel')),
            ],
        ),
    ]
