# Generated by Django 4.2.24 on 2025-10-25 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diaryapp', '0003_dailyactivities'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Day', models.DateField(blank=True, null=True)),
                ('ExpenseType', models.CharField(blank=True, max_length=100, null=True)),
                ('Description', models.TextField(blank=True, null=True)),
                ('Amount', models.FloatField(blank=True, null=True)),
                ('USERID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='diaryapp.usermodel')),
            ],
        ),
    ]
