# Generated by Django 4.2.24 on 2025-10-25 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaryapp', '0004_expensetable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensetable',
            name='Day',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
