# Generated by Django 4.2.24 on 2025-10-25 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaryapp', '0005_alter_expensetable_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensetable',
            name='Day',
            field=models.DateField(blank=True, null=True),
        ),
    ]
