# Generated by Django 4.2.24 on 2025-10-28 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaryapp', '0006_alter_expensetable_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyactivities',
            name='mood',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
