# Generated by Django 4.2.24 on 2025-10-28 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diaryapp', '0007_dailyactivities_mood'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyactivities',
            name='Title',
        ),
    ]
