# Generated by Django 4.2.24 on 2025-10-28 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diaryapp', '0008_remove_dailyactivities_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.FloatField(blank=True, null=True)),
                ('USERID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='diaryapp.usermodel')),
            ],
        ),
    ]
