# Generated by Django 4.2.24 on 2025-10-29 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaryapp', '0009_salarytable'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarytable',
            name='Day',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salarytable',
            name='Description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
