# Generated by Django 4.2.24 on 2025-10-29 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diaryapp', '0010_salarytable_day_salarytable_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReminderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(blank=True, null=True)),
                ('Time', models.TimeField(blank=True, null=True)),
                ('Reminder', models.TextField(blank=True, null=True)),
                ('USERID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='diaryapp.usermodel')),
            ],
        ),
    ]
