# Generated by Django 4.2.24 on 2025-12-31 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaryapp', '0011_remindermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginmodel',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='loginmodel',
            name='otp_verified',
            field=models.BooleanField(default=False),
        ),
    ]
